# Main configuration file for the project.

name:           green-zone
version:        1.0.0
synopsis:       OpenAPS. Rethink.
description:    OpenAPS. Rethink.
maintainer:     Denis Shevchenko <me@dshevchenko.biz>
github:         denisshevchenko/green-zone
license:        MIT
category:       Medical

# Common dependencies both for app and lib.
dependencies:
    - base < 5

library:
    source-dirs: lib/src
    dependencies:
        - aeson             == 1.2.4.0
        - async             == 2.1.1.1
        - binary            == 0.8.3.0
        - bytestring        == 0.10.8.1
        - directory         == 1.2.7.1
        - filepath          == 1.4.1.0
        # - http-client
        # - http-client-tls
        - pretty-terminal   == 0.1.0.0
        - safe-exceptions   == 0.1.6.0
        - shelly            == 1.7.0.1
        - stm               == 2.4.5.0
        - text              == 1.2.2.2
        - time              == 1.6.0.1
        - yaml              == 0.8.28
        - unix              == 2.7.2.0
    ghc-options: -Wall -Werror -Wno-orphans -fprint-potential-instances -O0

executables:
    green-zone:
        main:         Main.hs
        source-dirs:  app/src
        dependencies:
            - async           == 2.1.1.1
            - green-zone      == 1.0.0
            - safe-exceptions == 0.1.6.0
        ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O0

    green-zone-manager:
        main:         Main.hs
        source-dirs:  manager/src
        dependencies:
            - containers   == 0.5.7.1
            - green-zone   == 1.0.0
            - shelly       == 1.7.0.1
            - text         == 1.2.2.2
            - transformers == 0.5.2.0
        ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O0

tests:
    lib-tests:
        main:         Spec.hs
        source-dirs:  lib/test
        dependencies:
            - green-zone == 1.0.0
            - hspec      == 2.4.4
            - QuickCheck == 2.10.1
